Repository le2sky/mealkitary-server, pull requests merged in 2023-09, with the labels that each got.

#63 [기능 구현] 예약 거절 기능 구현(issue#62)
  gradle.properties
  mealkitary-api/src/docs/asciidoc/reservation.adoc
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/adapter/input/web/RejectReservationController.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/RejectReservationControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/WebIntegrationTestSupport.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/reservation/adapter/input/web/RejectReservationControllerTest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/port/input/RejectReservationUseCase.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/port/output/LoadPaymentPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/port/output/SendRejectedReservationMessagePort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/service/PayReservationService.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/service/RejectReservationService.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/reservation/application/service/RejectReservationServiceTest.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/reservation/domain/payment/ConfirmPaymentService.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/reservation/domain/payment/Payment.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/reservation/domain/payment/PaymentGatewayService.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/reservation/domain/payment/PaymentStatus.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/reservation/domain/payment/service/CancelPaymentService.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/reservation/domain/payment/service/ConfirmPaymentService.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/reservation/domain/payment/PaymentTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/reservation/domain/payment/service/CancelPaymentServiceTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/reservation/domain/payment/service/ConfirmPaymentServiceTest.kt
  mealkitary-infrastructure/adapter-firebase-notification/src/main/kotlin/com/mealkitary/common/firebase/FirebaseNotificationAdapter.kt
  mealkitary-infrastructure/adapter-firebase-notification/src/main/kotlin/com/mealkitary/common/firebase/FirebaseNotificationClient.kt
  mealkitary-infrastructure/adapter-firebase-notification/src/main/kotlin/com/mealkitary/common/firebase/message/ReservationStatusChangedMessage.kt
  mealkitary-infrastructure/adapter-firebase-notification/src/test/kotlin/com/mealkitary/common/firebase/FirebaseNotificationAdapterTest.kt
  mealkitary-infrastructure/adapter-paymentgateway-tosspayments/src/main/kotlin/com/mealkitary/reservation/adapter/output/paymentgateway/TossPaymentCancelPayload.kt
  mealkitary-infrastructure/adapter-paymentgateway-tosspayments/src/main/kotlin/com/mealkitary/reservation/adapter/output/paymentgateway/TossPaymentGatewayService.kt
  mealkitary-infrastructure/adapter-paymentgateway-tosspayments/src/main/kotlin/com/mealkitary/reservation/adapter/output/paymentgateway/TossPaymentWebClient.kt
  mealkitary-infrastructure/adapter-paymentgateway-tosspayments/src/test/kotlin/com/mealkitary/reservation/adapter/output/paymentgateway/TossPaymentGatewayServiceTest.kt
  mealkitary-infrastructure/adapter-paymentgateway-tosspayments/src/test/kotlin/com/mealkitary/reservation/adapter/output/paymentgateway/TossPaymentWebClientCancelTest.kt
  mealkitary-infrastructure/adapter-paymentgateway-tosspayments/src/test/kotlin/com/mealkitary/reservation/adapter/output/paymentgateway/TossPaymentWebClientConfirmTest.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/reservation/adapter/output/persistence/PaymentRepository.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/reservation/adapter/output/persistence/SpringDataJpaReservationPersistenceAdapter.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/PersistenceIntegrationTestSupport.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/reservation/adapter/output/persistence/SpringDataJpaReservationPersistenceAdapterTest.kt
Labels: new, run: gpt code review, run: ci

#67 [개선] 웹 모듈 패키지 구조 개선(issue#66)
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/AcceptReservationController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/GetReservationController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/PayReservationController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/RejectReservationController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/ReserveProductController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/request/PayReservationWebRequest.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/request/ReserveProductWebRequest.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/request/ReservedWebProduct.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/GetProductController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/GetReservableTimeController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/GetShopController.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/AcceptReservationControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/GetReservationControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/PayReservationControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/RejectReservationControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/ReserveProductControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/GetProductControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/GetReservableTimeControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/GetShopControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/WebIntegrationTestSupport.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/reservation/web/AcceptReservationControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/reservation/web/GetReservationControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/reservation/web/PayReservationControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/reservation/web/RejectReservationControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/reservation/web/ReserveProductControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/GetProductControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/GetReservableTimeControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/GetShopControllerTest.kt
Labels: enhancement, run: gpt code review, run: ci

#73 [문서] 협업 가이드 문서 작성(issue#67)
  docs/tech.md
Labels: documentation

#74 [배포] 메인 브랜치 반영(PR#73)
  docs/tech.md
Labels: no-deployment

#75 [기능 구현] 가게 식별자 기반 예약 조회 기능 구현(issue#70)
  mealkitary-api/src/docs/asciidoc/reservation.adoc
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/GetReservationController.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/GetReservationControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/reservation/web/GetReservationControllerTest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/port/input/GetReservationQuery.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/port/output/LoadReservationPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/service/GetReservationService.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/reservation/application/service/GetReservationServiceTest.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/reservation/persistence/ReservationRepository.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/reservation/persistence/SpringDataJpaReservationPersistenceAdapter.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/reservation/persistence/SpringDataJpaReservationPersistenceAdapterTest.kt
Labels: new, run: ci

#76 [기능 구현] 가게 상태 변경 기능 구현(issue#72)
  gradlew
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/UpdateShopStatusController.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/UpdateShopStatusControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/WebIntegrationTestSupport.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/UpdateShopStatusControllerTest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/UpdateShopStatusUseCase.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/output/CheckExistenceShopPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/UpdateShopStatusService.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/UpdateShopStatusServiceTest.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/Shop.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/ShopStatus.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopStatusTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopTest.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/reservation/persistence/ReservationRepository.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/shop/persistence/SpringDataJpaShopPersistenceAdapter.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/resources/data.sql
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/PersistenceIntegrationTestSupport.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/shop/persistence/SpringDataJpaShopPersistenceAdapterTest.kt
Labels: new, run: ci

#77 [기능 구현] 신규 가게 등록 기능 구현(issue#71)
  .github/workflows/mealkitary-main-develop-ci.yml
  .github/workflows/mealkitary-test-coverage-automation.yml
  gradle.properties
  mealkitary-api/build.gradle.kts
  mealkitary-api/src/docs/asciidoc/shop.adoc
  mealkitary-api/src/main/kotlin/com/mealkitary/common/utils/HttpResponseUtils.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/RegisterShopController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/request/RegisterShopWebRequest.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/GetReservationControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/RegisterShopControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/WebIntegrationTestSupport.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/RegisterShopControllerTest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/RegisterShopRequest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/RegisterShopUseCase.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/output/SaveShopPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/GetShopService.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/RegisterShopService.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/GetShopServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/RegisterShopServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/UpdateShopStatusServiceTest.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/Shop.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/ShopBusinessNumber.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/ShopTitle.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/ShopBusinessNumberValidator.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactory.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopBusinessNumberTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopTitleTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactoryTest.kt
  mealkitary-domain/src/testFixtures/kotlin/data/ShopTestData.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/reservation/persistence/SpringDataJpaReservationPersistenceAdapter.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/shop/persistence/SpringDataJpaShopPersistenceAdapter.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/resources/data.sql
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/PersistenceIntegrationTestSupport.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/shop/persistence/SpringDataJpaShopPersistenceAdapterTest.kt
  mealkitary-infrastructure/business-registration-number-validator/adapter-open-api-brn-validator/build.gradle.kts
  mealkitary-infrastructure/business-registration-number-validator/adapter-simple-brn-validator/build.gradle.kts
  mealkitary-infrastructure/business-registration-number-validator/adapter-simple-brn-validator/src/main/kotlin/com/mealkitary/brn/SimpleBrnValidator.kt
  mealkitary-infrastructure/business-registration-number-validator/adapter-simple-brn-validator/src/test/kotlin/com/mealkitary/brn/SimpleBrnValidatorTest.kt
  settings.gradle.kts
Labels: new, run: ci

#78 [배포] v0.5.0(PR#75,PR#76,PR#77)
  .github/workflows/mealkitary-main-develop-ci.yml
  .github/workflows/mealkitary-test-coverage-automation.yml
  gradle.properties
  gradlew
  mealkitary-api/build.gradle.kts
  mealkitary-api/src/docs/asciidoc/reservation.adoc
  mealkitary-api/src/docs/asciidoc/shop.adoc
  mealkitary-api/src/main/kotlin/com/mealkitary/common/utils/HttpResponseUtils.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/GetReservationController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/RegisterShopController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/UpdateShopStatusController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/request/RegisterShopWebRequest.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/GetReservationControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/RegisterShopControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/UpdateShopStatusControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/WebIntegrationTestSupport.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/reservation/web/GetReservationControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/RegisterShopControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/UpdateShopStatusControllerTest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/port/input/GetReservationQuery.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/port/output/LoadReservationPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/service/GetReservationService.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/RegisterShopRequest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/RegisterShopUseCase.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/UpdateShopStatusUseCase.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/output/CheckExistenceShopPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/output/SaveShopPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/GetShopService.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/RegisterShopService.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/UpdateShopStatusService.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/reservation/application/service/GetReservationServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/GetShopServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/RegisterShopServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/UpdateShopStatusServiceTest.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/Shop.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/ShopBusinessNumber.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/ShopStatus.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/ShopTitle.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/ShopBusinessNumberValidator.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactory.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopBusinessNumberTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopStatusTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopTitleTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactoryTest.kt
  mealkitary-domain/src/testFixtures/kotlin/data/ShopTestData.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/reservation/persistence/ReservationRepository.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/reservation/persistence/SpringDataJpaReservationPersistenceAdapter.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/shop/persistence/SpringDataJpaShopPersistenceAdapter.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/resources/data.sql
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/PersistenceIntegrationTestSupport.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/reservation/persistence/SpringDataJpaReservationPersistenceAdapterTest.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/shop/persistence/SpringDataJpaShopPersistenceAdapterTest.kt
  mealkitary-infrastructure/business-registration-number-validator/adapter-open-api-brn-validator/build.gradle.kts
  mealkitary-infrastructure/business-registration-number-validator/adapter-simple-brn-validator/build.gradle.kts
  mealkitary-infrastructure/business-registration-number-validator/adapter-simple-brn-validator/src/main/kotlin/com/mealkitary/brn/SimpleBrnValidator.kt
  mealkitary-infrastructure/business-registration-number-validator/adapter-simple-brn-validator/src/test/kotlin/com/mealkitary/brn/SimpleBrnValidatorTest.kt
  settings.gradle.kts
Labels: deployment, run: ci
