Repository le2sky/mealkitary-server, pull requests merged in 2023-10, with the labels that each got.

#82 [개선] 가게 생성 시 주소 정보 추가 (issue#79)
  .github/workflows/mealkitary-main-develop-ci.yml
  .github/workflows/mealkitary-test-coverage-automation.yml
  mealkitary-api/build.gradle.kts
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/request/RegisterShopWebRequest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/RegisterShopControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/RegisterShopControllerTest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/RegisterShopRequest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/RegisterShopService.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/GetShopServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/RegisterShopServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/UpdateShopStatusServiceTest.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/common/model/Address.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/common/model/Coordinates.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/Shop.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/address/ShopAddress.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/AddressResolver.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactory.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/AddressTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/CoordinatesTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopAddressTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactoryTest.kt
  mealkitary-domain/src/testFixtures/kotlin/data/ShopTestData.kt
  mealkitary-infrastructure/adapter-address-resolver/build.gradle.kts
  mealkitary-infrastructure/adapter-address-resolver/src/main/kotlin/com/mealkitary/address/SimpleAddressResolver.kt
  mealkitary-infrastructure/adapter-address-resolver/src/test/kotlin/SimpleAddressResolverTest.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/resources/data.sql
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/PersistenceIntegrationTestSupport.kt
  settings.gradle.kts
Labels: enhancement, run: ci

#81 [기능 구현] 국세청 사업자등록정보 상태조회 서비스 연동(issue#80)
  .github/workflows/mealkitary-main-develop-ci.yml
  .github/workflows/mealkitary-test-coverage-automation.yml
  gradle.properties
  mealkitary-api/build.gradle.kts
  mealkitary-infrastructure/adapter-address-resolver/build.gradle.kts
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/build.gradle.kts
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/main/kotlin/com/mealkitary/brn/OpenApiBrnValidator.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/main/kotlin/com/mealkitary/brn/OpenApiWebClient.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/main/kotlin/com/mealkitary/brn/payload/OpenApiBrnStatus.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/main/kotlin/com/mealkitary/brn/payload/OpenApiBrnStatusPayload.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/main/kotlin/com/mealkitary/brn/payload/OpenApiBrnStatusResponse.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/test/kotlin/com/mealkitary/brn/OpenApiBrnValidatorTest.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/test/kotlin/com/mealkitary/brn/OpenApiWebClientTest.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/simple-brn-validator/build.gradle.kts
  mealkitary-infrastructure/adapter-business-registration-number-validator/simple-brn-validator/src/main/kotlin/com/mealkitary/brn/SimpleBrnValidator.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/simple-brn-validator/src/test/kotlin/com/mealkitary/brn/SimpleBrnValidatorTest.kt
  mealkitary-infrastructure/adapter-configuration/build.gradle.kts
  mealkitary-infrastructure/adapter-configuration/src/main/kotlin/com/mealkitary/config/WebClientConfig.kt
  mealkitary-infrastructure/business-registration-number-validator/adapter-simple-brn-validator/build.gradle.kts
  settings.gradle.kts
Labels: new, run: ci

#83 [배포] v0.5.1(PR#81,PR#82)
  .github/workflows/mealkitary-main-develop-ci.yml
  .github/workflows/mealkitary-test-coverage-automation.yml
  gradle.properties
  mealkitary-api/build.gradle.kts
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/request/RegisterShopWebRequest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/RegisterShopControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/RegisterShopControllerTest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/RegisterShopRequest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/RegisterShopService.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/GetShopServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/RegisterShopServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/UpdateShopStatusServiceTest.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/common/model/Address.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/common/model/Coordinates.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/Shop.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/address/ShopAddress.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/AddressResolver.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactory.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/AddressTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/CoordinatesTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopAddressTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactoryTest.kt
  mealkitary-domain/src/testFixtures/kotlin/data/ShopTestData.kt
  mealkitary-infrastructure/adapter-address-resolver/build.gradle.kts
  mealkitary-infrastructure/adapter-address-resolver/src/main/kotlin/com/mealkitary/address/SimpleAddressResolver.kt
  mealkitary-infrastructure/adapter-address-resolver/src/test/kotlin/SimpleAddressResolverTest.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/build.gradle.kts
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/main/kotlin/com/mealkitary/brn/OpenApiBrnValidator.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/main/kotlin/com/mealkitary/brn/OpenApiWebClient.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/main/kotlin/com/mealkitary/brn/payload/OpenApiBrnStatus.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/main/kotlin/com/mealkitary/brn/payload/OpenApiBrnStatusPayload.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/main/kotlin/com/mealkitary/brn/payload/OpenApiBrnStatusResponse.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/test/kotlin/com/mealkitary/brn/OpenApiBrnValidatorTest.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/open-api-brn-validator/src/test/kotlin/com/mealkitary/brn/OpenApiWebClientTest.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/simple-brn-validator/build.gradle.kts
  mealkitary-infrastructure/adapter-business-registration-number-validator/simple-brn-validator/src/main/kotlin/com/mealkitary/brn/SimpleBrnValidator.kt
  mealkitary-infrastructure/adapter-business-registration-number-validator/simple-brn-validator/src/test/kotlin/com/mealkitary/brn/SimpleBrnValidatorTest.kt
  mealkitary-infrastructure/adapter-configuration/build.gradle.kts
  mealkitary-infrastructure/adapter-configuration/src/main/kotlin/com/mealkitary/config/WebClientConfig.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/resources/data.sql
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/PersistenceIntegrationTestSupport.kt
  mealkitary-infrastructure/business-registration-number-validator/adapter-simple-brn-validator/build.gradle.kts
  settings.gradle.kts
Labels: deployment, run: ci

#86 [기능 구현] 카카오 주소 조회 api 연동 (issue#84)
  .github/workflows/mealkitary-main-develop-ci.yml
  .github/workflows/mealkitary-test-coverage-automation.yml
  mealkitary-api/build.gradle.kts
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/RegisterShopServiceTest.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/AddressResolver.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactory.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactoryTest.kt
  mealkitary-infrastructure/adapter-address-resolver/build.gradle.kts
  mealkitary-infrastructure/adapter-address-resolver/kakao-api-address-resolver/build.gradle.kts
  mealkitary-infrastructure/adapter-address-resolver/kakao-api-address-resolver/src/main/kotlin/com/mealkitary/address/KakaoApiAddressResolver.kt
  mealkitary-infrastructure/adapter-address-resolver/kakao-api-address-resolver/src/main/kotlin/com/mealkitary/address/KakaoApiWebClient.kt
  mealkitary-infrastructure/adapter-address-resolver/kakao-api-address-resolver/src/main/kotlin/com/mealkitary/address/payload/KakaoApiAddressResponse.kt
  mealkitary-infrastructure/adapter-address-resolver/kakao-api-address-resolver/src/test/kotlin/com/mealkitary/addess/KakaoApiAddressResolverTest.kt
  mealkitary-infrastructure/adapter-address-resolver/kakao-api-address-resolver/src/test/kotlin/com/mealkitary/addess/KakaoApiWebClientTest.kt
  mealkitary-infrastructure/adapter-address-resolver/simple-address-resolver/build.gradle.kts
  mealkitary-infrastructure/adapter-address-resolver/simple-address-resolver/src/main/java/com/mealkitary/SimpleAddressResolver.kt
  mealkitary-infrastructure/adapter-address-resolver/simple-address-resolver/src/test/kotlin/com/mealkitary/address/SimpleAddressResolverTest.kt
  settings.gradle.kts
Labels: new, run: ci

#87 [개선] Shop 엔티티 식별자 UUID로 개선(issue#85)
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/GetReservationController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/reservation/web/request/ReserveProductWebRequest.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/GetProductController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/GetReservableTimeController.kt
  mealkitary-api/src/main/kotlin/com/mealkitary/shop/web/UpdateShopStatusController.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/GetReservationControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/reservation/ReserveProductControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/GetProductControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/GetReservableTimeControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/GetShopControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/RegisterShopControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/docs/shop/UpdateShopStatusControllerDocsTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/reservation/web/GetReservationControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/reservation/web/ReserveProductControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/GetProductControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/GetReservableTimeControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/GetShopControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/RegisterShopControllerTest.kt
  mealkitary-api/src/test/kotlin/com/mealkitary/shop/web/UpdateShopStatusControllerTest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/port/input/GetReservationQuery.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/port/input/ReserveProductRequest.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/port/output/LoadReservationPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/reservation/application/service/GetReservationService.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/GetProductQuery.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/GetReservableTimeQuery.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/RegisterShopUseCase.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/ShopResponse.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/input/UpdateShopStatusUseCase.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/output/CheckExistenceShopPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/output/LoadProductPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/output/LoadReservableTimePort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/output/LoadShopPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/port/output/SaveShopPort.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/GetProductService.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/GetReservableTimeService.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/RegisterShopService.kt
  mealkitary-application/src/main/kotlin/com/mealkitary/shop/application/service/UpdateShopStatusService.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/reservation/application/service/GetReservationServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/reservation/application/service/ReserveProductServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/GetProductServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/GetReservableTimeServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/GetShopServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/RegisterShopServiceTest.kt
  mealkitary-application/src/test/kotlin/com/mealkitary/shop/application/service/UpdateShopStatusServiceTest.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/Shop.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/ShopAddress.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/AddressResolver.kt
  mealkitary-domain/src/main/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactory.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/ShopAddressTest.kt
  mealkitary-domain/src/test/kotlin/com/mealkitary/shop/domain/shop/factory/ShopFactoryTest.kt
  mealkitary-domain/src/testFixtures/kotlin/data/ShopTestData.kt
  mealkitary-infrastructure/adapter-address-resolver/kakao-api-address-resolver/src/main/kotlin/com/mealkitary/address/KakaoApiAddressResolver.kt
  mealkitary-infrastructure/adapter-address-resolver/simple-address-resolver/src/main/java/com/mealkitary/SimpleAddressResolver.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/reservation/persistence/ReservationRepository.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/reservation/persistence/SpringDataJpaReservationPersistenceAdapter.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/shop/persistence/ShopRepository.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/kotlin/com/mealkitary/shop/persistence/SpringDataJpaShopPersistenceAdapter.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/main/resources/data.sql
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/reservation/persistence/SpringDataJpaReservationPersistenceAdapterTest.kt
  mealkitary-infrastructure/adapter-persistence-spring-data-jpa/src/test/kotlin/com/mealkitary/shop/persistence/SpringDataJpaShopPersistenceAdapterTest.kt
Labels: enhancement, run: ci
